### ISSUE TITLE
[50、获取用户的购物车信息]建议添加

### ISSUE THREAD

**Issue by hansonfang** [fuyunwang/ChengFeng1.5#7]
1. 建议添加商品图片
2. 能够批量删除购物车内商品
3. 商品属性里包含商品种类字段，如颜色，尺寸

**Comment by fuyunwang** [comment]
已经添加
/chengfeng/cart/listall

**Comment by fuyunwang** [comment]
更新购物车信息
/chengfeng/cart/update/{skuId}/{count}

PUT请求 skuid为商品id count为商品数量

**Comment by fuyunwang** [comment]
同时 ，在添加到购物车数据的同时，商品的属性信息如颜色尺寸已经添加

**Comment by fuyunwang** [comment]
/chengfeng/cart/delete/{skuId}
删除购物车中的商品
